<?php

/**
 * Do not edit this file.
 */

require_once( 'vendor/autoload.php' );

require_once( 'config/wp-config.php' );

define( 'WP_CONTENT_DIR', dirname(__FILE__) . '/wp-content' );
define( 'WP_POST_REVISIONS', 30 );

if ( !defined( 'ABSPATH' ) )
	define( 'ABSPATH', dirname(__FILE__) . '/wordpress/' );

require_once( ABSPATH . 'wp-settings.php' );
